//
//  FavouritedNewsInteractor.swift
//  NewsApp-VIP
//
//  Created by Burak YAZICI on 22/08/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavouritedNewsBusinessLogic
{
  func doSomething(request: FavouritedNews.Something.Request)
}

protocol FavouritedNewsDataStore
{
  //var name: String { get set }
}

class FavouritedNewsInteractor: FavouritedNewsBusinessLogic, FavouritedNewsDataStore
{
  var presenter: FavouritedNewsPresentationLogic?
  var worker: FavouritedNewsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: FavouritedNews.Something.Request)
  {
    worker = FavouritedNewsWorker()
    worker?.doSomeWork()
    
    let response = FavouritedNews.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
