//
//  FavouritedNewsPresenter.swift
//  NewsApp-VIP
//
//  Created by Burak YAZICI on 22/08/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavouritedNewsPresentationLogic
{
  func presentSomething(response: FavouritedNews.Something.Response)
}

class FavouritedNewsPresenter: FavouritedNewsPresentationLogic
{
  weak var viewController: FavouritedNewsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: FavouritedNews.Something.Response)
  {
    let viewModel = FavouritedNews.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
