//
//  NewsDetailInteractor.swift
//  NewsApp-VIP
//
//  Created by Burak YAZICI on 22/08/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewsDetailBusinessLogic
{
  func doSomething(request: NewsDetail.Something.Request)
}

protocol NewsDetailDataStore
{
  //var name: String { get set }
}

class NewsDetailInteractor: NewsDetailBusinessLogic, NewsDetailDataStore
{
  var presenter: NewsDetailPresentationLogic?
  var worker: NewsDetailWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: NewsDetail.Something.Request)
  {
    worker = NewsDetailWorker()
    worker?.doSomeWork()
    
    let response = NewsDetail.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
