//
//  NewsDetailPresenter.swift
//  NewsApp-VIP
//
//  Created by Burak YAZICI on 22/08/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewsDetailPresentationLogic
{
  func presentNews(response: NewsDetail.FetchNews.Response)
}

class NewsDetailPresenter: NewsDetailPresentationLogic
{
  weak var viewController: NewsDetailDisplayLogic?
  
  // MARK: Do something
  
  func presentNews(response: NewsDetail.FetchNews.Response)
  {
      let displayedNews = NewsDetail.FetchNews.ViewModel.DisplayedNews(urlToImage: response.news.urlToImage, title: response.news.title, articleDescription: response.news.articleDescription)
    let viewModel = NewsDetail.FetchNews.ViewModel(displayedNews: displayedNews)
    viewController?.displayFetchedNews(viewModel: viewModel)
  }
}
