//
//  NewsDetailWorker.swift
//  NewsApp-VIP
//
//  Created by Burak YAZICI on 22/08/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


class NewsDetailWorker {
    var service: ServicesProtocol
    
    init(service: ServicesProtocol) {
        self.service = service
    }
    func fetchNews(completion: @escaping (Result<[NewsResponseModel]?>) -> Void) {
        service.getTopHeadlines { result in
            DispatchQueue.main.async {
                completion(result)
            }
            
        }
    }
}
