//
//  NewsListPresenter.swift
//  NewsApp-VIP
//
//  Created by Burak YAZICI on 22/08/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewsListPresentationLogic
{
  func presentSomething(response: NewsList.FetchNews.Response)
}

class NewsListPresenter: NewsListPresentationLogic
{
  weak var viewController: NewsListDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: NewsList.FetchNews.Response)
  {
      var displayedNews : [NewsList.FetchNews.ViewModel.DisplayedNews] = []
      
      for news in response.news {
          let displayedNews = NewsList.FetchNews.ViewModel.DisplayedNews(id: news.id, urlToImage: news.urlToImage, title: news.title, articleDescription: news.articleDescription)
          displayedNews.append(displayedNews)
      }
    
      
      let viewModel = NewsList.FetchNews.ViewModel(displayedNews: displayedNews)
      viewController?.displayFetchedNews(viewModel: viewModel)
  }
}
