//
//  NewsListRouter.swift
//  NewsApp-VIP
//
//  Created by Burak YAZICI on 22/08/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol NewsListRoutingLogic
{
  func routeToNewsDetail(segue: UIStoryboardSegue?)
}

protocol NewsListDataPassing
{
  var dataStore: NewsListDataStore? { get }
}

class NewsListRouter: NSObject, NewsListRoutingLogic, NewsListDataPassing
{
    
    
  weak var viewController: NewsListViewController?
  var dataStore: NewsListDataStore?
  
  // MARK: Routing
  
  func routeToNewsDetail(segue: UIStoryboardSegue?)
  {
    if let segue = segue {
      let destinationVC = segue.destination as! NewsListViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToNewsDetail(source: dataStore!, destination: &destinationDS)
    } else {
        let destinationVC = viewController?.storyboard?.instantiateViewController(withIdentifier: "NewsDetailViewController") as! NewsDetailViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToNewsDetail(source: dataStore!, destination: &destinationDS)
      navigateToNewsDetail(source: viewController!, destination: destinationVC)
    }
  }

  // MARK: Navigation
  
  func navigateToNewsDetail(source: NewsListViewController, destination: NewsDetailViewController)
  {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  func passDataToNewsDetail(source: NewsListDataStore, destination: inout NewsDetailDataStore)
  {
      let selectedRow = viewController?.tableView.indexPathForSelectedRow?.row
      destination.news = source.news?[selectedRow!]
  }
}
