//
//  NewsListInteractor.swift
//  NewsApp-VIP
//
//  Created by Burak YAZICI on 22/08/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol NewsListBusinessLogic
{
  func fetchNews(request: NewsList.FetchNews.Request)
}

protocol NewsListDataStore
{
    var news: [NewsResponseModel]? { get }
}

class NewsListInteractor: NewsListBusinessLogic, NewsListDataStore
{
  var presenter: NewsListPresentationLogic?
  var worker: NewsListWorker?
    
  var news: [NewsResponseModel]?
 
  
  // MARK: Do something
  
  func fetchNews(request: NewsList.FetchNews.Request)
  {
      worker = NewsListWorker(service: APIService())
      worker?.fetchNews(completion: { (news, error) in
          if error != nil {
              //TODO: Run Clean swift error method
          } else {
              self.news = news
              let response = NewsList.FetchNews.Response(news: news)
              self.presenter?.presentNews(response: response)
          }
      })
    
  }
}
